export type NivelTecnicoMSZ =
  | 'INICIACION'
  | 'A'
  | 'A+'
  | 'B'
  | 'B+'
  | 'C'
  | 'C+'
  | 'D'
  | 'D+';

export type FaseTecnicaMSZ =
  | 'FAMILIARIZACION'
  | 'DESLIZAMIENTO'
  | 'CUNA'
  | 'GIROS_CUNA'
  | 'FUNDAMENTAL'
  | 'INICIO_PARALELO'
  | 'PARALELO_ELEMENTAL'
  | 'PARALELO_CONSOLIDADO'
  | 'CONDUCIDO';

export type ObjetivoTecnicoMSZ =
  | 'confianza'
  | 'equilibrio'
  | 'cuna'
  | 'frenada'
  | 'giro'
  | 'autonomia_cinta'
  | 'dinamica_grupo'
  | 'velocidad'
  | 'postura'
  | 'apoyo_exterior'
  | 'cantos'
  | 'ritmo'
  | 'precision'
  | 'paralelo'
  | 'coordinacion'
  | 'reto';

export type EjercicioTecnicoMSZ = {
  id: string;
  nombre: string;
  descripcion: string;
  niveles: NivelTecnicoMSZ[];
  pista: 'PEQUENA' | 'GRANDE' | 'AMBAS';
  zona:
    | 'CUALQUIERA'
    | 'FINAL_PISTA'
    | 'DESDE_MENOS_MITAD_GRANDE'
    | 'PISTA_PEQUENA';
  objetivos: ObjetivoTecnicoMSZ[];
  intensidad: 'BAJA' | 'MEDIA' | 'ALTA';
  formato: '1VS1' | 'GRUPO' | 'AMBOS';
  requiereBastones?: boolean;
  juego?: boolean;
  reto?: boolean;
  evitarSi?: string[];
  instrucciones: string;
  explicacionEntrenador?: string;
  progresion?: string;
  regresion?: string;
  variantesPorNivel?: Partial<Record<NivelTecnicoMSZ, string>>;
  variantesPorFase?: Partial<Record<FaseTecnicaMSZ, string>>;
};

const I: NivelTecnicoMSZ[] = ['INICIACION', 'A', 'A+'];
const BAJO_MEDIO: NivelTecnicoMSZ[] = ['A', 'A+', 'B', 'B+'];
const MEDIO: NivelTecnicoMSZ[] = ['B', 'B+', 'C', 'C+'];
const AVANZADO: NivelTecnicoMSZ[] = ['C', 'C+', 'D', 'D+'];
const TODOS: NivelTecnicoMSZ[] = [
  'INICIACION',
  'A',
  'A+',
  'B',
  'B+',
  'C',
  'C+',
  'D',
  'D+',
];

export const EJERCICIOS_TECNICOS_MSZ: EjercicioTecnicoMSZ[] = [
  {
    id: 'deslizamiento-profesor',
    nombre: 'Deslizamiento hasta el profesor',
    descripcion: 'Bajada corta 1vs1 con referencia clara de llegada.',
    niveles: I,
    pista: 'PEQUENA',
    zona: 'PISTA_PEQUENA',
    objetivos: ['confianza', 'equilibrio', 'frenada'],
    intensidad: 'BAJA',
    formato: '1VS1',
    instrucciones:
      'El profesor se coloca como referencia; el niño desliza, mantiene postura y termina frenando junto a él.',
  },
  {
    id: 'pizza-grande-pequena',
    nombre: 'Pizza grande / pizza pequeña',
    descripcion: 'Modificar la apertura de cuña para sentir el control de velocidad.',
    niveles: I,
    pista: 'PEQUENA',
    zona: 'PISTA_PEQUENA',
    objetivos: ['cuna', 'frenada', 'equilibrio'],
    intensidad: 'BAJA',
    formato: '1VS1',
    juego: true,
    instrucciones:
      'Alternar cuña pequeña para deslizar y cuña más grande para reducir velocidad, sin forzar una apertura exagerada.',
  },
  {
    id: 'semaforo-inicial',
    nombre: 'Semáforo',
    descripcion: 'Verde desliza, amarillo controla, rojo para.',
    niveles: I,
    pista: 'PEQUENA',
    zona: 'PISTA_PEQUENA',
    objetivos: ['frenada', 'confianza', 'coordinacion'],
    intensidad: 'BAJA',
    formato: '1VS1',
    juego: true,
    instrucciones:
      'Usar consignas verbales del profesor. Rojo debe terminar en parada controlada.',
  },
  {
    id: 'gigante-pequeno',
    nombre: 'Gigante / pequeño',
    descripcion: 'Cambios de postura simples para mejorar equilibrio y atención.',
    niveles: TODOS,
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'postura', 'coordinacion'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    juego: true,
    variantesPorNivel: {
      A: 'Alternar alto/bajo en cuña a velocidad muy controlada.',
      'A+': 'Cambiar altura sin romper los giros enlazados.',
      B: 'Marcar flexión y extensión dentro de giros amplios en cuña.',
      'B+': 'Usar el cambio de altura para facilitar la transición hacia Fundamental.',
      C: 'Flexión/extensión suave sin perder el paralelo.',
      'C+': 'Cambiar altura manteniendo ritmo y apoyo exterior.',
      D: 'Variar amplitud de flexión sin perder precisión de cantos.',
      'D+': 'Usarlo como contraste postural dentro de viraje conducido.',
    },
    instrucciones:
      'Alternar postura alta y postura compacta sin perder control ni mirar a los esquís.',
  },
  {
    id: 'seguir-huella',
    nombre: 'Seguir la huella del entrenador',
    descripcion: 'Copiar la trayectoria del profesor.',
    niveles: TODOS,
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'ritmo', 'dinamica_grupo', 'precision'],
    intensidad: 'MEDIA',
    formato: 'AMBOS',
    instrucciones:
      'El entrenador marca una línea adecuada al nivel y el niño/grupo copia distancia, radio y velocidad.',
  },
  {
    id: 'serpiente',
    nombre: 'Serpiente',
    descripcion: 'Todos siguen al entrenador encadenando giros.',
    niveles: BAJO_MEDIO,
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'ritmo', 'dinamica_grupo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    juego: true,
    instrucciones:
      'Mantener distancia clara; el entrenador adapta radio y velocidad para que nadie tenga que bajar recto.',
  },
  {
    id: 'parar-profesor',
    nombre: 'Parar detrás del profesor',
    descripcion: 'Control de velocidad, atención y distancia.',
    niveles: ['A', 'A+', 'B'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['frenada', 'dinamica_grupo', 'precision'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    instrucciones:
      'El niño debe terminar el giro y parar detrás del profesor, sin adelantar ni llegar con exceso de velocidad.',
  },
  {
    id: 'giro-aislado',
    nombre: 'Giro aislado derecha / izquierda',
    descripcion: 'Trabajar una dirección cada vez antes de enlazar.',
    niveles: ['A', 'A+'],
    pista: 'PEQUENA',
    zona: 'PISTA_PEQUENA',
    objetivos: ['giro', 'cuna'],
    intensidad: 'BAJA',
    formato: '1VS1',
    instrucciones:
      'Primero giro amplio a un lado, después al otro. No exigir continuidad hasta que ambos lados funcionen.',
  },
  {
    id: 'giros-amplios-cuna',
    nombre: 'Giros amplios en cuña',
    descripcion: 'Encadenar giros redondos controlando velocidad.',
    niveles: ['A+', 'B', 'B+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'frenada', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'AMBOS',
    instrucciones:
      'Acabar cada giro antes de iniciar el siguiente; velocidad controlada por trayectoria, no por frenadas bruscas.',
  },
  {
    id: 'tocar-botas',
    nombre: 'Tocar botas',
    descripcion: 'Juego para flexión, equilibrio y conciencia corporal.',
    niveles: ['A+', 'B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio', 'coordinacion'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    juego: true,
    variantesPorNivel: {
      'A+': 'Tocar botas solo en tramo fácil y volver a posición alta antes del siguiente giro.',
      B: 'Tocar botas entre giros para sentir flexión sin perder la cuña.',
      'B+': 'Tocar botas y recuperar postura antes de entrar en el siguiente giro.',
      C: 'Tocar botas manteniendo esquís paralelos y mirada al frente.',
      'C+': 'Usarlo como contraste de flexión dentro de una bajada fluida.',
    },
    instrucciones:
      'Tocar brevemente las botas en una zona fácil, manteniendo mirada al frente y velocidad controlada.',
  },
  {
    id: 'manos-delante',
    nombre: 'Manos visibles delante',
    descripcion: 'Consigna de postura y equilibrio.',
    niveles: TODOS,
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    variantesPorNivel: {
      A: 'Manos visibles delante mientras controla la cuña; una sola consigna: no mirar los esquís.',
      'A+': 'Manos delante mientras enlaza giros en cuña y mantiene distancia.',
      B: 'Manos delante durante toda la curva para estabilizar tronco y no sentarse.',
      'B+': 'Manos delante durante diagonal y extensión, buscando que la cuña se reduzca.',
      C: 'Manos delante manteniendo paralelo y apoyo exterior.',
      'C+': 'Manos delante sin rigidez mientras mantiene ritmo y trayectoria.',
      D: 'Consigna postural dentro de ejercicios de precisión o ritmo.',
      'D+': 'Usarla solo como recordatorio dentro de trabajo técnico más exigente.',
    },
    instrucciones:
      'Mantener manos visibles delante durante toda la bajada; combinar con otro ejercicio, no usar como única tarea.',
  },
  {
    id: 'avion',
    nombre: 'Avión',
    descripcion: 'Brazos abiertos para equilibrio lateral y apoyo exterior.',
    niveles: ['B', 'B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'apoyo_exterior', 'postura'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'Brazos abiertos; bajar ligeramente el brazo exterior para sentir el apoyo sin inclinar el tronco.',
      'B+': 'En Fundamental, usar el avión para mantener equilibrio lateral y acabar el giro.',
      C: 'En paralelo elemental, buscar apoyo exterior con tronco estable.',
      'C+': 'Mantener avión más fino, sin exagerar brazos, priorizando angulación y ritmo.',
      D: 'Usarlo solo como corrección puntual si pierde apoyo exterior.',
    },
    instrucciones:
      'Brazos abiertos y tronco estable; buscar apoyo exterior sin inclinarse de forma exagerada.',
  },
  {
    id: 'palmada-rodilla-exterior',
    nombre: 'Palmada en rodilla exterior',
    descripcion: 'Refuerzo sencillo del apoyo exterior.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'giro', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'Palmada suave en rodilla exterior al final de cada giro en cuña.',
      'B+': 'Palmada exterior mientras intenta cerrar esquís en diagonal.',
      C: 'Palmada exterior en paralelo elemental manteniendo mirada al frente.',
      'C+': 'Gesto corto para recordar apoyo exterior sin romper el ritmo.',
    },
    instrucciones:
      'En cada giro tocar/palmear suavemente la rodilla exterior sin hundirse ni perder mirada al frente.',
  },
  {
    id: 'levantar-interior',
    nombre: 'Levantar ligeramente esquí interior',
    descripcion: 'Comprobar equilibrio sobre el esquí exterior.',
    niveles: ['B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones:
      'Levantar solo unos instantes el esquí interior durante el giro, con velocidad media y total control.',
  },
  {
    id: 'pasillo-ancho',
    nombre: 'Pasillo imaginario ancho',
    descripcion: 'Regular trayectoria sin material externo.',
    niveles: MEDIO,
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['precision', 'giro', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Imaginar dos líneas y mantener los giros dentro de ese ancho; el entrenador marca visualmente el recorrido.',
  },
  {
    id: 'pasillo-estrecho',
    nombre: 'Pasillo imaginario estrecho',
    descripcion: 'Giros más cortos y precisos sin conos.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['precision', 'ritmo', 'giro'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Reducir el ancho de trayectoria solo si el grupo ya controla velocidad y giro medio.',
  },
  {
    id: 'cambio-radio',
    nombre: 'Cambio de radio',
    descripcion: 'Alternar giros amplios y más cortos.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['ritmo', 'precision', 'giro'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Alternar varios giros amplios con varios más cortos manteniendo postura y control de velocidad.',
  },
  {
    id: 'giro-corto-controlado',
    nombre: 'Giro corto controlado',
    descripcion: 'Ritmo y coordinación sin buscar velocidad máxima.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['ritmo', 'precision', 'cantos'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    instrucciones:
      'Secuencia corta de giros rápidos pero controlados; detener el ejercicio si se pierde trayectoria o postura.',
  },
  {
    id: 'derrapaje-lateral',
    nombre: 'Derrapaje lateral',
    descripcion: 'Sensibilidad de cantos y control lateral.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'equilibrio', 'precision'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    instrucciones:
      'En zona despejada, soltar y recuperar canto con velocidad baja y control total.',
  },
  {
    id: 'hoja-muerta',
    nombre: 'Hoja muerta',
    descripcion: 'Control adelante/atrás y de cantos.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'equilibrio', 'coordinacion'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    instrucciones:
      'Desplazamiento lateral muy controlado alternando dirección; solo en zona despejada y con autonomía suficiente.',
  },
  {
    id: 'un-esqui-final',
    nombre: 'Un solo esquí en tramo final',
    descripcion: 'Equilibrio, apoyo exterior y control fino.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'FINAL_PISTA',
    objetivos: ['equilibrio', 'apoyo_exterior', 'reto'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    reto: true,
    instrucciones:
      'Quitar un esquí únicamente en el tramo final, con espacio y velocidad controlada. Una bajada/serie corta y volver a dos esquís.',
  },
  {
    id: 'marcha-atras',
    nombre: 'Marcha atrás controlada',
    descripcion: 'Coordinación, equilibrio y percepción.',
    niveles: ['B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'FINAL_PISTA',
    objetivos: ['coordinacion', 'equilibrio', 'reto'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    reto: true,
    instrucciones:
      'Tramo corto, despejado y a velocidad baja. El entrenador controla espacio y final del ejercicio.',
  },
  {
    id: 'chuss-bolita',
    nombre: 'Chuss / bolita',
    descripcion: 'Posición aerodinámica y estabilidad a velocidad.',
    niveles: ['B', 'B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'DESDE_MENOS_MITAD_GRANDE',
    objetivos: ['velocidad', 'postura', 'equilibrio', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones:
      'Nunca desde arriba de pista grande. Empezar desde algo menos de mitad de pista hacia abajo y solo con salida despejada.',
  },
  {
    id: 'chuss-saltos-alternos',
    nombre: 'Chuss con saltos alternos',
    descripcion: 'Posición compacta con pequeños saltos controlados.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'DESDE_MENOS_MITAD_GRANDE',
    objetivos: ['equilibrio', 'coordinacion', 'velocidad', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones:
      'Desde algo menos de mitad de pista, nunca desde arriba. Saltos pequeños, alternos y solo si el niño mantiene la línea y la recepción estable.',
  },
  {
    id: 'velocidad-max-controlada',
    nombre: 'Velocidad máxima controlada',
    descripcion: 'Reto de velocidad con zona de salida limitada.',
    niveles: ['B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'DESDE_MENOS_MITAD_GRANDE',
    objetivos: ['velocidad', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones:
      'Nunca desde arriba. Salida desde algo menos de mitad de pista y únicamente si el entrenador valida control, espacio y zona de frenada.',
  },
  {
    id: 'carrera-final',
    nombre: 'Carrera final controlada',
    descripcion: 'Cierre lúdico con objetivo de control y trayectoria.',
    niveles: ['B', 'B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'FINAL_PISTA',
    objetivos: ['ritmo', 'precision', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    juego: true,
    reto: true,
    instrucciones:
      'Salida escalonada o uno a uno; no carrera simultánea ocupando toda la pista. Gana quien mantenga control y línea, no solo quien llegue antes.',
  },
  {
    id: 'bajada-libre-observada',
    nombre: 'Bajada libre observada',
    descripcion: 'Diagnóstico o cierre para comprobar transferencia.',
    niveles: TODOS,
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'giro', 'ritmo', 'precision'],
    intensidad: 'MEDIA',
    formato: 'AMBOS',
    instrucciones:
      'Sin consigna nueva. El entrenador observa si el trabajo técnico aparece de forma natural.',
  },
  {
    id: 'seguir-lider',
    nombre: 'Seguir al líder',
    descripcion: 'Juego de imitación y ritmo.',
    niveles: TODOS,
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'ritmo', 'dinamica_grupo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    juego: true,
    instrucciones:
      'El entrenador es líder y cambia una sola consigna cada vez: postura, radio o velocidad.',
  },
  {
    id: 'tren',
    nombre: 'Tren',
    descripcion: 'Dinámica de grupo y distancia.',
    niveles: ['A+', 'B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['dinamica_grupo', 'ritmo', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    juego: true,
    instrucciones:
      'Mantener orden y distancia constante siguiendo la misma línea; sin adelantar.',
  },
  {
    id: 'bastones-manos',
    nombre: 'Bastones horizontales delante',
    descripcion: 'Estabilidad de brazos y tronco.',
    niveles: AVANZADO,
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones:
      'Solo desde nivel C y únicamente si el grupo lleva bastones. Mantenerlos horizontales delante sin bloquear los brazos.',
  },

  {
    id: 'cierre-paralelo-final-giro',
    nombre: 'Cerrar esquís al final del giro',
    descripcion: 'Transición progresiva de cuña a paralelo.',
    niveles: ['B+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['paralelo', 'giro', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Entrar al giro con control y buscar que los esquís terminen juntos al finalizar la curva, sin forzar el cierre al principio.',
  },
  {
    id: 'paralelo-entre-giros',
    nombre: 'Paralelo entre giros',
    descripcion: 'Mantener ambos esquís paralelos durante la transición.',
    niveles: ['B+', 'C', 'C+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['paralelo', 'equilibrio', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Terminar la curva, juntar los esquís y mantener el paralelo durante la transición antes de iniciar el siguiente giro.',
  },
  {
    id: 'huella-dos-rail',
    nombre: 'Dos raíles',
    descripcion: 'Sentir cantos dejando dos huellas limpias.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'paralelo', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'En tramo fácil, inclinar suavemente ambos esquís para buscar dos huellas limpias y reducir derrapaje.',
  },
  {
    id: 'conducido-amplio',
    nombre: 'Giro conducido amplio',
    descripcion: 'Curvas amplias utilizando cantos y apoyo exterior.',
    niveles: ['D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'apoyo_exterior', 'precision', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Giros amplios, redondos y progresivos buscando apoyo exterior y que el esquí dibuje la curva sin derrapar en exceso.',
  },
  {
    id: 'conducido-cambio-radio',
    nombre: 'Conducido con cambio de radio',
    descripcion: 'Mantener cantos al variar amplitud de curva.',
    niveles: ['D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'precision', 'ritmo', 'coordinacion'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    instrucciones:
      'Alternar curvas conducidas amplias y más cortas manteniendo presión, apoyo exterior y continuidad.',
  },

  {
    id: 'cuna-pista-grande-controlada',
    nombre: 'Cuña en pista grande',
    descripcion: 'Consolidar giros y control de velocidad en terreno más largo.',
    niveles: ['B'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cuna', 'frenada', 'giro', 'dinamica_grupo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Giros amplios en cuña siguiendo al entrenador, terminando cada curva para controlar velocidad sin bajar recto.',
  },
  {
    id: 'paralelo-amplio-fluido',
    nombre: 'Paralelo amplio y fluido',
    descripcion: 'Estabilizar el paralelo en giros amplios con ritmo continuo.',
    niveles: ['C', 'C+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['paralelo', 'ritmo', 'apoyo_exterior', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Giros amplios y redondos manteniendo ambos esquís paralelos, apoyo exterior y una transición fluida.',
  },

  {
    id: 'simulacro-fila-a-plus',
    nombre: 'Simulacro de pista grande en fila',
    descripcion: 'Preparar la dinámica real antes de pasar a pista grande.',
    niveles: ['A+'],
    pista: 'PEQUENA',
    zona: 'PISTA_PEQUENA',
    objetivos: ['dinamica_grupo', 'giro', 'frenada', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Todos preparados arriba. Salen en orden, siguen la línea del entrenador, mantienen distancia y paran juntos donde marque.',
    explicacionEntrenador:
      'Haz la bajada como si ya estuvierais en grande: fila, distancia, misma línea y parada conjunta.',
    progresion:
      'Si lo hacen sin ayuda constante, valorar una prueba controlada en pista grande.',
    regresion:
      'Si se rompe la fila, volver a salidas de uno en uno y reconstruir la dinámica.',
  },
  {
    id: 'dos-manos-rodilla-exterior',
    nombre: 'Dos manos a rodilla exterior',
    descripcion: 'Refuerzo visual del apoyo sobre el esquí exterior.',
    niveles: ['B', 'B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'postura', 'giro'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'En cuña, llevar las dos manos hacia la rodilla exterior durante la segunda mitad del giro, sin agacharse de golpe.',
      'B+': 'En Fundamental, acercar las manos a la rodilla exterior para sentir apoyo y cerrar el giro.',
      C: 'En paralelo elemental, acompañar el giro hacia la rodilla exterior manteniendo tronco estable.',
      'C+': 'Acentuar apoyo exterior sin desplazar todo el cuerpo hacia dentro.',
      D: 'Usarlo como corrección puntual de apoyo exterior dentro de un giro técnico.',
    },
    variantesPorFase: {
      GIROS_CUNA: 'Dos manos hacia la rodilla exterior mientras termina el giro en cuña.',
      FUNDAMENTAL: 'Dos manos hacia la rodilla exterior en el final del giro; buscar que los esquís vuelvan paralelos en diagonal.',
      INICIO_PARALELO: 'Tocar la rodilla exterior sin perder el paralelo que ya empieza a aparecer.',
      PARALELO_ELEMENTAL: 'Marcar apoyo exterior con tronco estable y manos controladas.',
    },
    instrucciones:
      'Durante cada giro llevar las dos manos hacia la rodilla exterior y volver al centro antes del siguiente cambio.',
    explicacionEntrenador:
      'En cada giro lleva las dos manos a la rodilla exterior; al terminar vuelve al centro antes de cambiar.',
    progresion:
      'Hacerlo con más ritmo o combinarlo con paralelo estable.',
    regresion:
      'Una sola mano a la rodilla exterior.',
  },
  {
    id: 'dos-manos-rodillas-palmada',
    nombre: 'Manos en rodillas + palmada delante',
    descripcion: 'Marcar flexión y extensión entre giros.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'ritmo', 'apoyo_exterior'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'Manos sobre las rodillas durante el giro; al extender antes del siguiente, palmada delante y volver a las rodillas.',
      'B+': 'En Fundamental, palmada delante durante la extensión y buscar esquís paralelos en la diagonal.',
      C: 'En paralelo elemental, palmada delante al cambiar de giro sin perder apoyo exterior.',
      'C+': 'Misma secuencia con más continuidad y menos gesto exagerado.',
    },
    variantesPorFase: {
      GIROS_CUNA: 'Rodillas durante la curva, palmada delante al extender para iniciar la siguiente.',
      FUNDAMENTAL: 'Rodillas en la curva, palmada delante en la extensión y esquís paralelos en diagonal.',
      INICIO_PARALELO: 'Palmada delante en el cambio de giro manteniendo el paralelo el mayor tiempo posible.',
      PARALELO_ELEMENTAL: 'Mantener ritmo: rodillas en flexión y palmada breve durante la extensión.',
    },
    instrucciones:
      'Manos en rodillas durante el giro; al terminar, hacer extensión con palmada delante y comenzar el siguiente giro.',
    explicacionEntrenador:
      'Baja con manos en rodillas; antes del nuevo giro estírate un poco y da una palmada delante.',
    progresion:
      'Aumentar continuidad y reducir la exageración del gesto.',
    regresion:
      'Hacer palmada solo cada dos giros.',
  },
  {
    id: 'cadera-palmada-espalda',
    nombre: 'Manos en cadera + palmada por detrás',
    descripcion: 'Coordinar extensión y cambio de giro.',
    niveles: ['B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      'B+': 'Manos en cadera durante el giro y palmada detrás solo en la extensión, sin forzar hombros.',
      C: 'En paralelo, mantener cadera estable y usar la palmada detrás para notar extensión.',
      'C+': 'Hacer el gesto más pequeño y mantener ritmo continuo.',
      D: 'Usarlo como contraste de coordinación, no como ejercicio principal de toda la sesión.',
    },
    variantesPorFase: {
      FUNDAMENTAL: 'Manos en cadera durante la curva; palmada detrás en la extensión y volver rápido a cadera.',
      INICIO_PARALELO: 'Palmada detrás durante el cambio de giro, manteniendo esquís paralelos.',
      PARALELO_ELEMENTAL: 'Coordinar flexión/extensión sin que la palmada rompa la trayectoria.',
    },
    instrucciones:
      'Manos en cadera durante el giro; en la extensión entre curvas hacer una palmada por detrás y volver a posición.',
    explicacionEntrenador:
      'Manos en cadera durante la curva; al cambiar de giro haz la extensión y una palmada por detrás.',
    progresion:
      'Hacerlo manteniendo paralelo fluido y ritmo constante.',
    regresion:
      'Palmada delante en vez de detrás.',
  },
  {
    id: 'avion-exterior-bota',
    nombre: 'Avioncito: mano exterior a bota',
    descripcion: 'Aumentar apoyo exterior y angulación de forma visual.',
    niveles: ['B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'cantos', 'postura'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      'B+': 'Solo si controla bien: bajar mano exterior hacia la bota en el final del giro, sin tocar si pierde equilibrio.',
      C: 'Bajar mano exterior hacia bota mientras la otra sube; mantener esquís paralelos.',
      'C+': 'Buscar una angulación más clara sin volcar el tronco.',
      D: 'Usarlo como ejercicio de precisión del apoyo exterior.',
    },
    instrucciones:
      'Bajar la mano exterior hacia la bota exterior mientras la mano interior sube, sin tumbar todo el cuerpo.',
    explicacionEntrenador:
      'En el giro baja la mano exterior hacia la bota exterior y levanta la interior; el cuerpo no se tumba entero.',
    progresion:
      'Reducir el gesto de brazos y mantener la misma sensación de apoyo exterior.',
    regresion:
      'Avión normal con brazos abiertos.',
  },
  {
    id: 'talon-interior-diagonal',
    nombre: 'Talón interior en diagonal',
    descripcion: 'Preparar el apoyo exterior antes del siguiente giro.',
    niveles: ['B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'paralelo', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      'B+': 'En diagonal estable, levantar solo el talón del futuro esquí interior durante un instante.',
      C: 'Extender, entrar en diagonal y levantar el talón interior para reforzar apoyo exterior.',
      'C+': 'Mantener el talón interior ligero durante más parte del giro.',
      D: 'Convertirlo en una corrección fina de presión exterior, no en levantar todo el esquí.',
    },
    instrucciones:
      'Al entrar en la diagonal levantar ligeramente el talón del futuro esquí interior; mantener la punta cerca de la nieve.',
    explicacionEntrenador:
      'En la diagonal levanta solo el talón del esquí que será interior en el siguiente giro; la punta casi toca la nieve.',
    progresion:
      'Pasar a levantar ligeramente todo el esquí interior durante parte del giro.',
    regresion:
      'Solo descargar el interior sin levantarlo.',
  },
  {
    id: 'giro-interior-levantado',
    nombre: 'Giro con esquí interior levantado',
    descripcion: 'Trabajo avanzado de apoyo exterior durante la curva.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'cantos', 'precision'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    instrucciones:
      'Levantar ligeramente el esquí interior durante parte del giro y completar la curva apoyado sobre el exterior.',
    explicacionEntrenador:
      'Durante parte de la curva levanta un poco el esquí interior y termina el giro sobre el exterior.',
    progresion:
      'Aumentar el tiempo con el interior levantado o enlazar varios giros.',
    regresion:
      'Levantar solo el talón interior en la diagonal.',
  },
  {
    id: 'tip-tap-sin-salto',
    nombre: 'Tip tap sin salto',
    descripcion: 'Cambio rápido de apoyos sin despegar los esquís.',
    niveles: ['D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'ritmo', 'cantos', 'precision'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    instrucciones:
      'Alternar rápidamente la presión entre esquís durante la transición sin despegar del suelo ni perder trayectoria.',
    explicacionEntrenador:
      'En el cambio de giro mueve rápido los apoyos de un esquí al otro, sin saltar ni perder la línea.',
    progresion:
      'Más ritmo o tip tap con pequeño salto.',
    regresion:
      'Pasos activos más lentos durante la transición.',
  },
  {
    id: 'tip-tap-con-salto',
    nombre: 'Tip tap con salto',
    descripcion: 'Cambio dinámico de apoyos con pequeño salto.',
    niveles: ['D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'ritmo', 'cantos', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    instrucciones:
      'Pequeño salto en la transición para cambiar apoyos, solo con niños muy fuertes y totalmente estables.',
    explicacionEntrenador:
      'Igual que el tip tap, pero con un pequeño salto en el cambio de giro. Solo con grupo muy avanzado.',
    progresion:
      'Enlazar varios cambios manteniendo precisión.',
    regresion:
      'Tip tap sin salto.',
  },
  {
    id: 'bastones-bandeja',
    nombre: 'Bastones en bandeja',
    descripcion: 'Estabilizar manos y tronco mientras se trabaja técnica.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'ritmo'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones:
      'Llevar los dos bastones horizontales delante como una bandeja y mantenerlos estables durante los giros.',
    explicacionEntrenador:
      'Lleva los bastones horizontales como una bandeja delante y haz los giros sin que la bandeja se incline.',
    progresion:
      'Combinar la bandeja con apoyo exterior o cambio de radio.',
    regresion:
      'Manos visibles delante sin bastones.',
  },
  {
    id: 'bastones-bandeja-extension',
    nombre: 'Bandeja + extensión',
    descripcion: 'Estabilidad de tronco y extensión entre giros.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones:
      'Bastones en bandeja durante el giro; elevar ligeramente la bandeja en la extensión y recuperar la posición al entrar en la nueva curva.',
    explicacionEntrenador:
      'Mantén la bandeja durante la curva; al cambiar de giro súbela un poco con la extensión y vuelve a colocarla.',
    progresion:
      'Hacerlo con más ritmo o radios distintos.',
    regresion:
      'Bandeja estable sin marcar extensión.',
  },
  {
    id: 'bastones-bandeja-apoyo',
    nombre: 'Bandeja + apoyo exterior',
    descripcion: 'Combinar estabilidad de brazos y carga exterior.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'apoyo_exterior', 'cantos', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones:
      'Mantener los bastones como bandeja mientras se busca apoyo exterior sin girar hombros.',
    explicacionEntrenador:
      'Bandeja quieta delante y, debajo, trabaja fuerte el esquí exterior sin girar los hombros.',
    progresion:
      'Combinar con conducción o cambios de radio.',
    regresion:
      'Bandeja normal.',
  },
  {
    id: 'parada-lateral',
    nombre: 'Parada lateral',
    descripcion: 'Control rápido de cantos y frenada con esquís paralelos.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'FINAL_PISTA',
    objetivos: ['cantos', 'frenada', 'precision', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Desde velocidad moderada girar ambos esquís hacia un lado y terminar parado con los esquís paralelos.',
    explicacionEntrenador:
      'Baja con velocidad moderada, gira los dos esquís juntos hacia un lado y acaba completamente parado en paralelo.',
    progresion:
      'Alternar lado derecho e izquierdo con menos preparación.',
    regresion:
      'Parada progresiva terminando el giro cuesta arriba.',
  },
  {
    id: 'derrapaje-recto-derrapaje',
    nombre: 'Derrapaje → recto → derrapaje',
    descripcion: 'Sensibilidad de cantos pasando de derrapar a dejar correr.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'equilibrio', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Empezar derrapando lateralmente, poner los esquís planos para dejarlos correr y volver a poner canto para recuperar el derrapaje.',
    explicacionEntrenador:
      'Empieza derrapando de lado, deja los esquís planos para que corran un poco y vuelve a poner canto para controlar otra vez.',
    progresion:
      'Hacer cambios más rápidos y simétricos a ambos lados.',
    regresion:
      'Derrapaje lateral simple.',
  },
  {
    id: 'giro-derrapado-esquis',
    nombre: 'Giro derrapado de esquís',
    descripcion: 'Rotar ambos esquís bajo un tronco relativamente estable.',
    niveles: ['D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'cantos', 'precision', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones:
      'Con el tronco estable, hacer girar los dos esquís juntos mientras derrapan de un lado al otro con poco avance.',
    explicacionEntrenador:
      'Tronco tranquilo; gira los dos esquís juntos debajo del cuerpo mientras derrapan de un lado al otro.',
    progresion:
      'Más continuidad y menor desplazamiento.',
    regresion:
      'Derrapaje lateral con cambio de dirección más lento.',
  },
  {
    id: 'pasos-activos-diagonal',
    nombre: 'Pasos activos en diagonal',
    descripcion: 'Independencia de piernas y movilidad sobre los esquís.',
    niveles: ['B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'coordinacion', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      'B+': 'Pequeños pasos en diagonal con esquís casi paralelos para ganar movilidad sin miedo.',
      C: 'Pasos cortos y activos en diagonal manteniendo tronco estable.',
      'C+': 'Aumentar continuidad de pasos sin romper trayectoria.',
      D: 'Pasos más rápidos para activar pies antes de trabajo de cantos.',
      'D+': 'Usar como activación técnica breve antes de tareas de conducción.',
    },
    instrucciones:
      'Durante una diagonal dar pequeños pasos alternos con los esquís manteniendo dirección y postura.',
    explicacionEntrenador:
      'En la diagonal da pequeños pasos alternando un esquí y otro, sin cambiar la dirección ni perder postura.',
    progresion:
      'Llevar los pasos a la transición entre giros.',
    regresion:
      'Levantar solo un talón cada vez.',
  },
  {
    id: 'saltitos-pequenos',
    nombre: 'Pequeños saltos sobre los esquís',
    descripcion: 'Coordinación, presión y recepción estable.',
    niveles: ['D', 'D+'],
    pista: 'GRANDE',
    zona: 'FINAL_PISTA',
    objetivos: ['coordinacion', 'equilibrio', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    instrucciones:
      'Hacer pequeños saltos verticales con ambos esquís, recepciones suaves y trayectoria estable.',
    explicacionEntrenador:
      'En un tramo fácil haz saltos pequeños con los dos esquís y busca caer suave sin perder la línea.',
    progresion:
      'Encadenar varios saltos con ritmo.',
    regresion:
      'Aligerar esquís sin llegar a despegar.',
  },
  {
    id: 'mismo-radio-cambio-ritmo',
    nombre: 'Mismo radio, distinto ritmo',
    descripcion: 'Mantener forma de curva cambiando la frecuencia.',
    niveles: ['D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['ritmo', 'precision', 'coordinacion'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    instrucciones:
      'Mantener un radio parecido pero alternar secuencias más dinámicas y más calmadas sin perder técnica.',
    explicacionEntrenador:
      'Haz curvas del mismo tamaño, pero cambia el ritmo: unas más rápidas y otras más tranquilas sin cambiar la forma.',
    progresion:
      'Combinar también cambios de radio.',
    regresion:
      'Mantener ritmo constante.',
  },
  {
    id: 'cambio-radio-mismo-ritmo',
    nombre: 'Distinto radio, mismo ritmo',
    descripcion: 'Cambiar tamaño de curva manteniendo cadencia.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['ritmo', 'precision', 'cantos'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    instrucciones:
      'Alternar curvas amplias y más cortas intentando mantener la misma cadencia de giro.',
    explicacionEntrenador:
      'Cambia el tamaño de las curvas, pero intenta mantener siempre el mismo ritmo de giro.',
    progresion:
      'Hacerlo en conducción más limpia.',
    regresion:
      'Cambiar radio sin exigir mantener ritmo.',
  },

  {
    id: 'manos-cadera',
    nombre: 'Manos en la cadera',
    descripcion: 'Estabilizar tronco y sentir flexión/extensión sin depender de los brazos.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio', 'coordinacion'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    explicacionEntrenador:
      'Esquiar con manos apoyadas en la cadera, tronco estable y mirada al frente; no convertirlo en postura rígida.',
    variantesPorNivel: {
      B: 'En cuña, manos en cadera durante varios giros amplios para evitar brazos desordenados.',
      'B+': 'En Fundamental, mantener cadera estable y notar mejor la extensión entre giros.',
      C: 'En paralelo elemental, estabilizar tronco mientras los pies realizan el giro.',
      'C+': 'Usarlo como corrección puntual de tronco antes de volver a esquiar con manos libres.',
    },
    instrucciones:
      'Serie corta de varios giros. Volver después a posición normal de brazos y comprobar transferencia.',
  },
  {
    id: 'manos-rodillas',
    nombre: 'Manos sobre las rodillas',
    descripcion: 'Sentir flexión y posición centrada durante la curva.',
    niveles: ['A+', 'B', 'B+', 'C'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio', 'coordinacion'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    explicacionEntrenador:
      'Apoyar suavemente las manos sobre las rodillas durante varios giros, sin empujarlas hacia dentro ni mirar abajo.',
    variantesPorNivel: {
      'A+': 'En cuña, notar las rodillas flexionadas sin sentarse.',
      B: 'Mantener flexión estable durante giros amplios en cuña.',
      'B+': 'En Fundamental, combinar flexión en curva y extensión en el cambio.',
      C: 'En paralelo elemental, mantener centrado el cuerpo mientras giran los pies.',
    },
    instrucciones:
      'No apretar las rodillas ni encorvar la espalda. Usar pocas curvas y volver a posición normal.',
  },
  {
    id: 'palmada-delante-extension',
    nombre: 'Palmada delante en la extensión',
    descripcion: 'Marcar el momento de extensión y cambio de giro.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'postura', 'giro', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'AMBOS',
    explicacionEntrenador:
      'Hacer una palmada delante justo al extender para iniciar el siguiente giro y volver enseguida a manos estables.',
    variantesPorFase: {
      GIROS_CUNA: 'Palmada delante al acabar un giro y extender antes del siguiente.',
      FUNDAMENTAL: 'Palmada durante la extensión y buscar esquís paralelos en la diagonal.',
      INICIO_PARALELO: 'Usar la palmada para ordenar el cambio de giro sin volver a abrir tanta cuña.',
      PARALELO_ELEMENTAL: 'Palmada pequeña y rápida para mantener ritmo de flexión/extensión.',
    },
    instrucciones:
      'Una palmada por cambio. Si el gesto altera mucho la trayectoria, reducir amplitud o volver a manos delante.',
  },
  {
    id: 'terminar-giro-cuesta-arriba',
    nombre: 'Terminar el giro hacia arriba',
    descripcion: 'Aprender a cerrar la curva y controlar velocidad mediante trayectoria.',
    niveles: ['A+', 'B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'frenada', 'precision', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'AMBOS',
    explicacionEntrenador:
      'Cerrar cada giro un poco más hacia la parte alta de la pista antes de iniciar el siguiente, sin frenazo brusco.',
    variantesPorNivel: {
      'A+': 'En cuña, acabar bien cada giro antes de cambiar de lado.',
      B: 'Usar la forma de la curva para controlar velocidad en pista grande.',
      'B+': 'Cerrar el giro y buscar esquís paralelos en la diagonal.',
      C: 'Mantener paralelo mientras termina la curva con apoyo exterior.',
      'C+': 'Ajustar cuánto cierra la curva sin romper ritmo.',
    },
    instrucciones:
      'El objetivo es controlar velocidad con la trayectoria. No convertirlo en atravesar toda la pista sin mirar.',
  },
  {
    id: 'diagonal-paralela',
    nombre: 'Diagonal con esquís paralelos',
    descripcion: 'Fijar la parte paralela del Fundamental y preparar el paralelo completo.',
    niveles: ['B+', 'C'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['paralelo', 'equilibrio', 'apoyo_exterior', 'precision'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    explicacionEntrenador:
      'Tras terminar el giro, mantener ambos esquís paralelos durante la diagonal antes de iniciar el siguiente.',
    variantesPorFase: {
      FUNDAMENTAL: 'Giro todavía en cuña, pero diagonal claramente paralela y estable.',
      INICIO_PARALELO: 'Alargar el tiempo en paralelo e intentar que aparezca antes durante el giro.',
    },
    instrucciones:
      'No forzar juntar esquís si pierde equilibrio; priorizar estabilidad y apoyo exterior.',
  },
  {
    id: 'reducir-cuna-progresiva',
    nombre: 'Reducir la cuña progresivamente',
    descripcion: 'Hacer la cuña cada vez menor sin perder control ni trayectoria.',
    niveles: ['B', 'B+', 'C'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cuna', 'paralelo', 'giro', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    explicacionEntrenador:
      'Mantener el mismo giro y reducir poco a poco la apertura de la cuña, sin obligar a cerrar los esquís de golpe.',
    variantesPorNivel: {
      B: 'Solo reducir un poco la cuña si mantiene frenada y dirección.',
      'B+': 'Buscar cuña pequeña en la entrada y esquís paralelos en la diagonal.',
      C: 'Usarlo solo si reaparece cuña: volver rápido al paralelo sin perder apoyo.',
    },
    instrucciones:
      'La prioridad es control. Si al reducir la cuña aumenta velocidad o pierde dirección, volver a la apertura anterior.',
  },
  {
    id: 'tocar-muslo-exterior',
    nombre: 'Tocar muslo exterior',
    descripcion: 'Introducir apoyo exterior con menos exigencia que llegar a la rodilla o bota.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'postura', 'giro'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    explicacionEntrenador:
      'En cada giro, tocar suavemente el muslo de la pierna exterior sin bajar demasiado el tronco.',
    variantesPorNivel: {
      B: 'En cuña, identificar cuál es la pierna exterior en cada giro.',
      'B+': 'En Fundamental, mantener presión exterior mientras cierra esquís en diagonal.',
      C: 'En paralelo elemental, reforzar apoyo exterior con tronco estable.',
      'C+': 'Reducir el gesto y usarlo solo como recordatorio de apoyo.',
    },
    instrucciones:
      'Alternar lado en cada giro. Si confunde exterior/interior, hacer primero giros aislados.',
  },
  {
    id: 'volante',
    nombre: 'Volante',
    descripcion: 'Manos delante como si sujetara un volante para ordenar postura y orientación.',
    niveles: ['A+', 'B', 'B+', 'C'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'giro'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    juego: true,
    explicacionEntrenador:
      'Imaginar un volante delante del cuerpo y mantenerlo estable; giran los esquís, no los hombros.',
    variantesPorNivel: {
      'A+': 'Volante quieto delante mientras enlaza giros en cuña.',
      B: 'Evitar que los hombros roten siguiendo cada curva.',
      'B+': 'Mantener volante estable mientras el giro pasa por Fundamental.',
      C: 'En paralelo, separar claramente trabajo de piernas y tronco.',
    },
    instrucciones:
      'No hacer girar exageradamente el volante. La imagen sirve para mantener manos delante y tronco estable.',
  },

  {
    id: 'parada-cuna-a-demanda',
    nombre: 'Parada en cuña a demanda',
    descripcion: 'Frenar cuando lo indica el entrenador sin anticiparse.',
    niveles: ['A', 'A+', 'B'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['frenada', 'velocidad', 'giro'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    instrucciones: 'El entrenador marca el momento de parar; el niño controla la velocidad y termina en cuña estable.',
  },
  {
    id: 'tres-giros-y-parada',
    nombre: 'Tres giros y parada',
    descripcion: 'Encadenar una secuencia corta y terminar con parada controlada.',
    niveles: ['A', 'A+', 'B', 'B+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'frenada', 'precision', 'dinamica_grupo'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    variantesPorNivel: {
      A: 'Tres giros en cuña y parar cerca del entrenador.',
      'A+': 'Tres giros enlazados, mantener distancia y parar sin ayuda.',
      B: 'Tres giros redondos en cuña controlando velocidad con la trayectoria.',
      'B+': 'Tres giros cerrados buscando esquís paralelos en la diagonal.',
    },
    instrucciones: 'Secuencia fácil de repetir para comprobar control, dirección y final de curva.',
  },
  {
    id: 'curva-grande-curva-pequena',
    nombre: 'Curva grande / curva pequeña',
    descripcion: 'Alternar radios sencillos para aprender a modificar trayectoria.',
    niveles: ['A+', 'B', 'B+', 'C'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'precision', 'ritmo', 'velocidad'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      'A+': 'Una curva muy grande y otra algo más pequeña, siempre en cuña y con control.',
      B: 'Alternar radios manteniendo cuña estable y velocidad controlada.',
      'B+': 'Reducir cuña en la diagonal sin perder la diferencia de radio.',
      C: 'Mantener paralelo al cambiar el radio.',
    },
    instrucciones: 'Cambiar el tamaño del giro sin convertirlo en una bajada rápida.',
  },
  {
    id: 'giros-con-pausa',
    nombre: 'Giros con pausa en la diagonal',
    descripcion: 'Terminar cada giro, estabilizarse y continuar.',
    niveles: ['B', 'B+', 'C'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'equilibrio', 'precision', 'paralelo'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'Cerrar el giro en cuña, estabilizarse y comenzar el siguiente con calma.',
      'B+': 'Cerrar el giro y usar la pausa para colocar los esquís paralelos.',
      C: 'Mantener paralelo y postura estable durante la pausa.',
    },
    instrucciones: 'La pausa es corta y sirve para ordenar el cuerpo, no para atravesar toda la pista.',
  },
  {
    id: 'guirnalda-cuna',
    nombre: 'Guirnalda en cuña',
    descripcion: 'Iniciar y cerrar parcialmente el mismo giro para sentir dirección y control.',
    niveles: ['A+', 'B', 'B+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['giro', 'frenada', 'equilibrio', 'apoyo_exterior'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    instrucciones: 'Repetir pequeñas entradas y salidas del giro hacia el mismo lado sin cruzar toda la pista.',
  },
  {
    id: 'guirnalda-paralela',
    nombre: 'Guirnalda con esquís paralelos',
    descripcion: 'Trabajar inicio de giro y cambio de presión manteniendo paralelo.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['paralelo', 'apoyo_exterior', 'cantos', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Desde una diagonal, iniciar varias veces el giro y volver a la diagonal manteniendo ambos esquís paralelos.',
  },
  {
    id: 'diagonal-manos-delante',
    nombre: 'Diagonal estable con manos delante',
    descripcion: 'Estabilizar postura y mirada antes del siguiente giro.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio', 'paralelo', 'precision'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'Mantener cuña pequeña y manos delante sin sentarse.',
      'B+': 'Buscar esquís paralelos en diagonal con manos visibles.',
      C: 'Mantener paralelo, tronco estable y mirada hacia la trayectoria.',
      'C+': 'Mantener postura estable mientras prepara el cambio de cantos.',
    },
    instrucciones: 'La diagonal es corta; evitar quedarse atravesado en pista.',
  },
  {
    id: 'rodillas-acompanan-giro',
    nombre: 'Rodillas acompañan el giro',
    descripcion: 'Mover las rodillas hacia el interior del giro sin rotar hombros.',
    niveles: ['B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'cantos', 'paralelo', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Mantener tronco tranquilo y dirigir suavemente ambas rodillas hacia el interior de cada curva.',
  },
  {
    id: 'tocar-rodilla-exterior-al-final',
    nombre: 'Tocar rodilla exterior al final',
    descripcion: 'Reforzar apoyo exterior en la segunda mitad del giro.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'postura', 'giro'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'En cuña, tocar suavemente la rodilla exterior al cerrar el giro.',
      'B+': 'Tocar la rodilla exterior y terminar con diagonal más paralela.',
      C: 'Mantener paralelo y tocar la rodilla exterior sin inclinar todo el tronco.',
      'C+': 'Usar el gesto solo como recordatorio y mantener ritmo fluido.',
    },
    instrucciones: 'No agacharse; el gesto debe ser breve.',
  },
  {
    id: 'mano-exterior-cadera',
    nombre: 'Mano exterior en la cadera',
    descripcion: 'Sentir estabilidad del lado exterior y controlar rotación.',
    niveles: ['B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'postura', 'coordinacion'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    instrucciones: 'Colocar la mano exterior en la cadera durante parte del giro y mantener la otra delante.',
  },
  {
    id: 'manos-sobre-muslos',
    nombre: 'Manos sobre los muslos',
    descripcion: 'Buscar flexión centrada sin sentarse.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    instrucciones: 'Apoyar las manos suavemente sobre los muslos y mantener tobillos y rodillas activos.',
  },
  {
    id: 'subir-bajar-postura',
    nombre: 'Subir y bajar la postura',
    descripcion: 'Alternar extensión y flexión de forma controlada.',
    niveles: ['B', 'B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio', 'coordinacion', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Subir suavemente en el cambio de giro y volver a flexionar durante la curva sin saltar.',
  },
  {
    id: 'extension-cambio-giro',
    nombre: 'Extensión en el cambio de giro',
    descripcion: 'Coordinar la extensión con el paso de un giro al siguiente.',
    niveles: ['B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'postura', 'giro', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Acabar el giro flexionado, extender suavemente al cambiar de lado y volver a construir apoyo.',
  },
  {
    id: 'dos-curvas-lentas-una-normal',
    nombre: 'Dos curvas lentas / una normal',
    descripcion: 'Cambiar ritmo manteniendo control y misma técnica.',
    niveles: ['B', 'B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['ritmo', 'giro', 'precision', 'velocidad'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Hacer dos giros muy redondos y lentos y después uno a ritmo normal sin acelerar de forma brusca.',
  },
  {
    id: 'tres-curvas-mismo-radio',
    nombre: 'Tres curvas con el mismo radio',
    descripcion: 'Repetir tres giros iguales para ganar regularidad.',
    niveles: ['B', 'B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['precision', 'ritmo', 'giro', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    variantesPorNivel: {
      B: 'Tres giros redondos en cuña del mismo tamaño.',
      'B+': 'Tres giros iguales buscando Fundamental estable.',
      C: 'Tres giros paralelos iguales con apoyo exterior claro.',
      'C+': 'Tres giros iguales manteniendo ritmo y trayectoria.',
      D: 'Tres giros iguales con cantos y presión consistentes.',
      'D+': 'Tres giros conducidos iguales y limpios.',
    },
    instrucciones: 'La calidad se mide por repetir la misma forma, no por ir más rápido.',
  },
  {
    id: 'cambiar-radio-cada-tres',
    nombre: 'Cambiar radio cada tres giros',
    descripcion: 'Tres giros amplios y tres más cerrados manteniendo control.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['precision', 'ritmo', 'cantos', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Hacer tres giros de un radio y cambiar a otro radio durante los tres siguientes sin perder ritmo.',
  },
  {
    id: 'acelerar-frenar-trayectoria',
    nombre: 'Acelerar y frenar con la trayectoria',
    descripcion: 'Usar curvas más abiertas o más cerradas para modificar velocidad.',
    niveles: ['B', 'B+', 'C', 'C+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['velocidad', 'giro', 'precision', 'frenada'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Abrir algo la línea para ganar velocidad y cerrar los giros para reducirla, sin frenazos.',
  },
  {
    id: 'seguir-huella-distancia',
    nombre: 'Seguir huella manteniendo distancia',
    descripcion: 'Copiar línea del entrenador y mantener un espacio constante.',
    niveles: ['A+', 'B', 'B+', 'C', 'C+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['dinamica_grupo', 'giro', 'precision', 'ritmo'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    instrucciones: 'Seguir la misma línea sin acercarse ni quedarse atrás; la distancia debe mantenerse durante toda la bajada.',
  },
  {
    id: 'fila-parada-conjunta',
    nombre: 'Fila y parada conjunta',
    descripcion: 'Trabajar orden de grupo, distancia y final de bajada.',
    niveles: ['A+', 'B', 'B+', 'C'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['dinamica_grupo', 'frenada', 'precision'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    instrucciones: 'Bajar en fila y terminar todos en la zona marcada por el entrenador manteniendo distancia.',
  },
  {
    id: 'espejo-profesor',
    nombre: 'Espejo del profesor',
    descripcion: 'Imitar postura y trayectoria del entrenador.',
    niveles: ['B', 'B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'postura', 'ritmo', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Copiar una sola característica de cada bajada: postura, radio o ritmo.',
  },
  {
    id: 'espejo-parejas',
    nombre: 'Espejo por parejas',
    descripcion: 'Un niño marca la línea y el otro la copia a distancia segura.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['precision', 'ritmo', 'dinamica_grupo', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Salida escalonada; el segundo copia la línea del primero sin acercarse demasiado.',
  },
  {
    id: 'giro-sobre-esqui-exterior',
    nombre: 'Giro sobre el esquí exterior',
    descripcion: 'Aligerar claramente el interior para reforzar el apoyo exterior.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'paralelo', 'precision'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    evitarSi: ['miedo', 'velocidad_sin_control'],
    instrucciones: 'Durante una parte del giro, aligerar el esquí interior y mantener el exterior estable.',
  },
  {
    id: 'diagonal-esqui-exterior',
    nombre: 'Diagonal sobre esquí exterior',
    descripcion: 'Mantener una diagonal corta apoyado principalmente en el esquí exterior.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Al terminar el giro, aligerar el interior unos instantes y mantener trayectoria estable.',
  },
  {
    id: 'toques-esqui-interior',
    nombre: 'Toques del esquí interior',
    descripcion: 'Dar pequeños toques con el interior para comprobar que el peso está fuera.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Levantar apenas el interior y tocar de nuevo la nieve varias veces durante una diagonal o giro amplio.',
  },
  {
    id: 'pasos-continuos-curva',
    nombre: 'Pasos continuos durante la curva',
    descripcion: 'Mover los pies activamente para mejorar equilibrio y centralidad.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'equilibrio', 'cantos', 'ritmo'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    evitarSi: ['miedo', 'velocidad_sin_control'],
    instrucciones: 'Dar pequeños pasos alternos durante giros amplios sin perder la línea ni la estabilidad.',
  },
  {
    id: 'pasos-cambio-giro',
    nombre: 'Pasos en el cambio de giro',
    descripcion: 'Usar dos o tres pasos en la transición para activar los pies.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'equilibrio', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Entre un giro y el siguiente, hacer dos o tres pasos pequeños manteniendo manos delante.',
  },
  {
    id: 'saltito-cambio-giro',
    nombre: 'Saltito en el cambio de giro',
    descripcion: 'Pequeño salto controlado en la transición para activar piernas.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'equilibrio', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones: 'Un salto pequeño y vertical en el cambio de giro, con velocidad baja y recepción estable.',
  },
  {
    id: 'flexion-profunda-controlada',
    nombre: 'Flexión profunda controlada',
    descripcion: 'Aumentar flexión durante el giro sin sentarse atrás.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Flexionar tobillos, rodillas y cadera durante el giro manteniendo el cuerpo centrado.',
  },
  {
    id: 'alto-bajo-por-giro',
    nombre: 'Alto al cambio / bajo en curva',
    descripcion: 'Coordinar extensión en transición y flexión en el giro.',
    niveles: ['B+', 'C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'ritmo', 'giro'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Estar algo más alto al cambiar de lado y volver a bajar progresivamente durante la curva.',
  },
  {
    id: 'mirada-siguiente-giro',
    nombre: 'Mirada al siguiente giro',
    descripcion: 'Anticipar la trayectoria con la mirada sin girar hombros.',
    niveles: ['B', 'B+', 'C', 'C+', 'D'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'precision', 'giro'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    instrucciones: 'Antes de terminar cada giro, mirar hacia dónde empezará el siguiente manteniendo hombros estables.',
  },
  {
    id: 'hombros-quietos-piernas-giran',
    nombre: 'Hombros quietos / piernas giran',
    descripcion: 'Separar movimiento de piernas y tronco.',
    niveles: ['B+', 'C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Mantener pecho orientado estable mientras las piernas realizan los cambios de dirección.',
  },
  {
    id: 'manos-a-la-altura-del-pecho',
    nombre: 'Manos visibles a la altura del pecho',
    descripcion: 'Evitar manos atrás y estabilizar tronco.',
    niveles: ['B', 'B+', 'C', 'C+', 'D', 'D+'],
    pista: 'AMBAS',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'equilibrio'],
    intensidad: 'BAJA',
    formato: 'AMBOS',
    instrucciones: 'Mantener ambas manos visibles delante durante toda la bajada sin juntarlas.',
  },
  {
    id: 'tocar-bota-exterior-final',
    nombre: 'Tocar bota exterior al final del giro',
    descripcion: 'Acentuar apoyo exterior y flexión lateral controlada.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'postura', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Al final del giro, bajar la mano exterior hacia la bota exterior sin colapsar el tronco.',
  },
  {
    id: 'brazos-cruzados-pecho',
    nombre: 'Brazos cruzados en el pecho',
    descripcion: 'Eliminar ayuda de brazos y sentir equilibrio de piernas.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'postura', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    evitarSi: ['miedo'],
    instrucciones: 'Cruzar brazos durante una bajada corta y mantener equilibrio solo con piernas y tronco.',
  },
  {
    id: 'manos-en-casco',
    nombre: 'Manos en el casco',
    descripcion: 'Reducir movimientos de brazos y trabajar estabilidad.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'postura', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    evitarSi: ['miedo'],
    instrucciones: 'Apoyar las manos suavemente en el casco durante un tramo corto manteniendo mirada al frente.',
  },
  {
    id: 'derrapaje-un-lado',
    nombre: 'Derrapaje a un solo lado',
    descripcion: 'Soltar cantos de forma sencilla antes de alternar ambos lados.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'equilibrio', 'precision'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    instrucciones: 'Desde una diagonal controlada, poner esquís más planos y dejar que deslicen lateralmente unos metros.',
  },
  {
    id: 'derrapaje-dos-lados',
    nombre: 'Derrapaje a ambos lados',
    descripcion: 'Alternar derrapaje lateral a derecha e izquierda.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'equilibrio', 'precision', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Realizar un derrapaje corto a un lado, parar, cambiar orientación y repetir al otro.',
  },
  {
    id: 'parada-hockey-derecha-izquierda',
    nombre: 'Parada hockey derecha / izquierda',
    descripcion: 'Parar de forma lateral por ambos lados.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'frenada', 'precision', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Alternar el lado de la parada lateral manteniendo velocidad moderada y espacio suficiente.',
  },
  {
    id: 'pivot-slip-simplificado',
    nombre: 'Pivot slip simplificado',
    descripcion: 'Cambiar orientación de los esquís con derrapaje controlado y tronco estable.',
    niveles: ['D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'coordinacion', 'precision', 'paralelo'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    evitarSi: ['miedo', 'velocidad_sin_control'],
    instrucciones: 'En una zona de pendiente moderada, orientar los esquís de un lado al otro mientras derrapan y el tronco permanece estable.',
  },
  {
    id: 'cambio-cantos-diagonal',
    nombre: 'Cambio de cantos desde diagonal',
    descripcion: 'Sentir el paso de un canto al otro antes del giro completo.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'paralelo', 'equilibrio'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Desde una diagonal estable, aplanar los esquís y cambiar suavemente al nuevo canto para iniciar dirección.',
  },
  {
    id: 'rodar-tobillos',
    nombre: 'Rodar tobillos hacia el nuevo canto',
    descripcion: 'Iniciar el cambio de cantos desde tobillos y piernas.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'coordinacion', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'En giros amplios, sentir cómo ambos tobillos pasan suavemente de un canto al otro.',
  },
  {
    id: 'canto-progresivo-giro',
    nombre: 'Más canto al avanzar el giro',
    descripcion: 'Aumentar inclinación de los esquís progresivamente durante la curva.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'precision', 'paralelo', 'apoyo_exterior'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Comenzar el giro con poco canto y aumentarlo progresivamente hasta la parte media-final.',
  },
  {
    id: 'soltar-cantos-final',
    nombre: 'Soltar cantos al terminar el giro',
    descripcion: 'Aprender a liberar los esquís para facilitar la transición.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['cantos', 'coordinacion', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Después de completar la curva, reducir presión y dejar los esquís más planos antes del siguiente cambio.',
  },
  {
    id: 'presion-exterior-progresiva',
    nombre: 'Presión exterior progresiva',
    descripcion: 'Construir apoyo exterior de forma gradual durante el giro.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'cantos', 'precision', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Empezar suave y aumentar el apoyo sobre el esquí exterior hasta la parte fuerte de la curva.',
  },
  {
    id: 'terminar-presion-y-soltar',
    nombre: 'Presionar y soltar',
    descripcion: 'Notar apoyo exterior y después liberar antes del siguiente giro.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'cantos', 'coordinacion', 'ritmo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Construir presión durante el giro y soltarla claramente al terminar para preparar el siguiente.',
  },
  {
    id: 'giro-un-esqui-alternando',
    nombre: 'Un giro con un esquí / un giro con dos',
    descripcion: 'Alternar apoyo exterior reforzado con giro normal.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'coordinacion', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    evitarSi: ['miedo', 'velocidad_sin_control'],
    instrucciones: 'En un giro aligerar claramente el interior; en el siguiente volver a esquiar normal y repetir.',
  },
  {
    id: 'medio-giro-esqui-exterior',
    nombre: 'Media curva sobre el exterior',
    descripcion: 'Mantener el interior muy ligero durante media curva.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'equilibrio', 'paralelo'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'Desde la línea de máxima pendiente hasta el final de la curva, aligerar el interior y mantener apoyo fuera.',
  },
  {
    id: 'bastones-delante-paralelos',
    nombre: 'Bastones paralelos delante',
    descripcion: 'Usar los bastones como referencia visual para estabilizar brazos.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['postura', 'coordinacion', 'paralelo'],
    intensidad: 'BAJA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones: 'Llevar ambos bastones delante, paralelos al suelo, sin permitir que roten con cada curva.',
  },
  {
    id: 'baston-exterior-delante',
    nombre: 'Bastón exterior delante',
    descripcion: 'Usar un bastón como referencia de apoyo exterior y orientación.',
    niveles: ['C', 'C+', 'D'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['apoyo_exterior', 'postura', 'coordinacion'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones: 'Mantener el bastón exterior visible delante durante la segunda mitad del giro.',
  },
  {
    id: 'toque-baston-simple',
    nombre: 'Toque de bastón simple',
    descripcion: 'Introducir un apoyo de bastón sencillo antes de iniciar el giro.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'ritmo', 'postura'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones: 'Hacer un toque ligero del bastón justo antes de iniciar el siguiente giro, sin clavar fuerte.',
  },
  {
    id: 'toque-baston-ritmo',
    nombre: 'Toque de bastón con ritmo',
    descripcion: 'Usar el bastón para mantener una cadencia regular de giros.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['coordinacion', 'ritmo', 'precision'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    requiereBastones: true,
    instrucciones: 'Mantener un toque de bastón regular antes de cada giro sin acelerar la secuencia.',
  },
  {
    id: 'mini-baches-imaginarios',
    nombre: 'Absorber pequeños cambios de terreno',
    descripcion: 'Flexionar y extender piernas como si hubiera pequeños cambios de relieve.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'coordinacion', 'postura'],
    intensidad: 'MEDIA',
    formato: 'GRUPO',
    instrucciones: 'En un tramo seguro, variar flexión de piernas manteniendo el tronco estable y la trayectoria limpia.',
  },
  {
    id: 'saltitos-en-diagonal',
    nombre: 'Pequeños saltos en diagonal',
    descripcion: 'Realizar saltos pequeños y controlados durante una diagonal corta.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'coordinacion', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones: 'Dos o tres saltos pequeños, verticales y controlados, con recepción equilibrada.',
  },
  {
    id: 'salto-y-dos-giros',
    nombre: 'Salto y dos giros',
    descripcion: 'Combinar un salto pequeño con dos giros técnicos posteriores.',
    niveles: ['D', 'D+'],
    pista: 'GRANDE',
    zona: 'CUALQUIERA',
    objetivos: ['equilibrio', 'coordinacion', 'precision', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones: 'Hacer un salto pequeño en zona segura y enlazar dos giros limpios después de la recepción.',
  },
  {
    id: 'bolita-salir-giro',
    nombre: 'Bolita y salir a giro',
    descripcion: 'Pasar de posición compacta a un giro controlado.',
    niveles: ['C', 'C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'DESDE_MENOS_MITAD_GRANDE',
    objetivos: ['velocidad', 'postura', 'giro', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones: 'Desde menos de mitad de pista, hacer un tramo corto en bolita y salir con un giro amplio y controlado.',
  },
  {
    id: 'bolita-frenada-lateral',
    nombre: 'Bolita y parada lateral',
    descripcion: 'Combinar posición rápida con una parada técnica controlada.',
    niveles: ['C+', 'D', 'D+'],
    pista: 'GRANDE',
    zona: 'DESDE_MENOS_MITAD_GRANDE',
    objetivos: ['velocidad', 'frenada', 'cantos', 'reto'],
    intensidad: 'ALTA',
    formato: 'GRUPO',
    reto: true,
    evitarSi: ['miedo', 'velocidad_sin_control', 'autonomia_baja'],
    instrucciones: 'Tramo corto en bolita desde menos de mitad y terminar con parada lateral limpia en zona segura.',
  },

];

export function normalizarNivelMSZ(
  valor: string | null | undefined
): NivelTecnicoMSZ {
  const limpio = String(valor || '')
    .toUpperCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();

  const detectado =
    limpio.match(
      /(?:^|[^A-Z])(INICIACION|DEBUT|A\+?|B\+{0,2}|C\+?|D\+?)(?:$|[^A-Z+])/i
    )?.[1] || limpio;

  if (detectado === 'INICIACION' || detectado === 'DEBUT') return 'INICIACION';
  if (detectado === 'B++') return 'B+';
  if (
    detectado === 'A' ||
    detectado === 'A+' ||
    detectado === 'B' ||
    detectado === 'B+' ||
    detectado === 'C' ||
    detectado === 'C+' ||
    detectado === 'D' ||
    detectado === 'D+'
  ) {
    return detectado;
  }
  return 'A+';
}

export const ORDEN_NIVEL_MSZ: Record<NivelTecnicoMSZ, number> = {
  INICIACION: 0,
  A: 1,
  'A+': 2,
  B: 3,
  'B+': 4,
  C: 5,
  'C+': 6,
  D: 7,
  'D+': 8,
};
