import type { EvaluacionTecnicaReporte } from '../reports/reportTypes';

export type EvaluationCut = 'NAVIDAD' | 'FINAL';

export type EvaluacionAnualOcioApp = {
  alumno_id: string;
  alumno: string;
  temporada: string;
  entrenamientos_ocio: number;
  sesiones_ocio_programadas: number;
  asistencia_ocio_pct: number | null;
  reportes_ocio: number;
  primer_reporte_fecha: string | null;
  ultimo_reporte_fecha: string | null;
  nivel_inicial: string | null;
  nivel_final: string | null;
  niveles_reportados: string | null;
  tecnica_inicial: string | null;
  tecnica_final: string | null;
  autonomia_inicial: string | null;
  autonomia_final: string | null;
  remontes_iniciales: string[] | null;
  remontes_finales: string[] | null;
  actitud_final: string | null;
  pista_final: string | null;
  recomendacion_final: string | null;
  comentario_tecnica_final: string | null;
  comentario_autonomia_final: string | null;
  trabajos_realizados: string | null;
  observaciones_grupo: string | null;
  observaciones_reportes: string | null;
  mejoras_reportadas: string | null;
  navidad_guardada: boolean;
  nivel_navidad: string | null;
  tecnica_navidad: string | null;
  autonomia_navidad: string | null;
  remontes_navidad: string[] | null;
  actitud_navidad: string | null;
  pista_navidad: string | null;
  recomendacion_navidad: string | null;
  trabajos_navidad: string | null;
  observaciones_grupo_navidad: string | null;
  observaciones_reportes_navidad: string | null;
};

export type CorteEvaluacionOcioApp = {
  snapshot_id: string;
  alumno_id: string;
  alumno: string;
  temporada: string;
  corte: EvaluationCut;
  dia_ocio: string | null;
  generado_at: string;
  reportes_ocio: number;
  nivel_inicial: string | null;
  nivel_corte: string | null;
};

export type ResumenFinalIntensivoApp = {
  intensivo_alumno_id: string;
  intensivo_id: string;
  intensivo: string;
  alumno_id: string;
  alumno: string;
  total_dias_intensivo: number;
  dias_en_grupo: number;
  dias_presente: number;
  dias_ausente: number;
  dias_pendiente_asistencia: number;
  total_reportes: number;
  reportes_pendientes_estimados: number;
  niveles_reportados: string | null;
  nivel_mas_alto_id: string | null;
  nivel_mas_alto_reportado: string | null;
  nivel_ultimo_reporte: string | null;
  actitud_ultimo_reporte: string | null;
  tecnica_ultimo_reporte: string | null;
  autonomia_ultimo_reporte: string | null;
  recomendacion_ultimo_reporte: string | null;
  ultimo_reporte_fecha: string | null;
  actitudes_reportadas: string | null;
  tecnicas_reportadas: string | null;
  pistas_reportadas: string | null;
  autonomias_reportadas: string | null;
  incidencias_reportadas: string | null;
  recomendaciones_reportadas: string | null;
  comentarios_actitud: string | null;
  comentarios_tecnica: string | null;
  comentarios_autonomia: string | null;
  comentarios_incidencias: string | null;
  comentarios_recomendacion: string | null;
  nivel_final_propuesto_id: string | null;
  nivel_final_propuesto: string | null;
  nivel_final_confirmado_id: string | null;
  nivel_final_confirmado: string | null;
  recomendacion_siguiente_paso: string | null;
  estado_diploma: string;
};

export type ReporteDetalleIntensivoApp = {
  intensivo_id: string;
  intensivo: string;
  intensivo_dia_id: string;
  numero_dia: number;
  fecha: string;
  hora_inicio: string;
  hora_fin: string;
  grupo_id: string;
  nombre_grupo: string;
  entrenador: string | null;
  alumno_id: string;
  alumno: string;
  nivel_reportado: string | null;
  actitud: string | null;
  actitud_comentario: string | null;
  tecnica: string | null;
  tecnica_comentario: string | null;
  pista: string | null;
  autonomia: string | null;
  autonomia_comentario: string | null;
  incidencia: string | null;
  incidencia_comentario: string | null;
  recomendacion_proxima_sesion: string | null;
  recomendacion_comentario: string | null;
  observaciones_generales?: string | null;
  enviado_at: string | null;
  evaluacion_tecnica?: EvaluacionTecnicaReporte | null;
  mejoras_hoy?: string[] | null;
  prioridades_proxima_sesion?: string[] | null;
  reporte_version?: number | null;
};
